name: 'dvdrental_project'
version: '1.0'
config-version: 2

profile: 'dvdrental'

models:
  dvdrental_project:
    
    schema: modelo_dimensional
    fact:
      hechos_alquileres:
        materialized: table
    dim:
      dim_cliente:
        materialized: table
      dim_pelicula:
        materialized: table
      dim_formato:
        materialized: table
      dim_promocion:
        materialized: table
      dim_tiempo:
        materialized: table
